---
- hosts: all
  become: yes

  tasks:

  - import_tasks: fix-authorized_keys.yml

  # 3. Our lab does not have the firewall enabled by default so we will install it as root. 
  - name: Remove firewalld lab package
    package:
      name: firewalld
      state: absent

#  - name: Enable and start firewalld.service
#    service:
#      name: firewalld
#      enabled: yes
#      state: started
