---
- name: Step 004 Environment specific Software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Deploy Roles if infra_workloads defined
  hosts:
    - nodes
  gather_facts: false
  run_once: false
  become: yes
  tags:
    - infra_workloads
  tasks:
  - name: apply infra workloads roles on nodes
    when:
    - infra_workloads|d("")|length > 0
    block:
      - name: Apply role "{{ workload_loop_var }}" on nodes
        include_role:
          name: "{{ workload_loop_var }}"
        vars:
          ACTION: "provision"
        loop: "{{ infra_workloads.split(',')|list }}"
        loop_control:
          loop_var: workload_loop_var

- name: Configure AIDE on RHEL 8 node1
  hosts: node1.*
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup AIDE
      import_tasks: aide.yml

- name: Configure gpg on RHEL 8 node 2
  hosts: node2.*
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup GPG
      import_tasks: gpg.yml

- name: Configure audit on RHEL 8 node 3
  hosts: node3.*
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup AUDIT
      import_tasks: audit.yml

- name: Configure firewalld on RHEL 8 node 4
  hosts: node4.*
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup firewalld
      import_tasks: firewalld.yml

- name: Configure IPSEC 1 on RHEL 8 node 5
  hosts: node5.*
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup IPSEC 1
      import_tasks: ipsec.yml

- name: Configure IPSEC 2 on RHEL 8 node 6
  hosts: node6.*
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup IPSEC 2
      import_tasks: ipsec.yml

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
