---
- name: Step 004 Environment specific Software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Configure software 
  hosts: all
  tasks:
  - name: Pull UBI images
    command: podman pull registry.access.redhat.com/ubi8/python-36
  - name: Pull registry image
    command: podman pull docker.io/library/registry:2
  - name: Copying files
    copy:
      src: files
      dest: $HOME

- name: Deploy Roles if infra_workloads defined
  hosts:
    - nodes
  gather_facts: false
  run_once: false
  become: yes
  tags:
    - infra_workloads
  tasks:
  - name: apply infra workloads roles on nodes
    when:
    - infra_workloads|d("")|length > 0
    block:
      - name: Apply role "{{ workload_loop_var }}" on nodes
        include_role:
          name: "{{ workload_loop_var }}"
        vars:
          ACTION: "provision"
        loop: "{{ infra_workloads.split(',')|list }}"
        loop_control:
          loop_var: workload_loop_var


- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"


- name: Configure AIDE on RHEL 8 node1
  hosts: node1.lkerner.internal
  become: yes
  tasks:
  - name: Remove aide if it's installed
    package:
      name: aide
      state: absent

  - name: Install required packages
    package:
      name:
        - audit
        - vim-minimal
      state: present 

- name: Configure gpg on RHEL 8 node 2
  hosts: node2.lkerner.internal
  become: yes 
  tasks: 
  - name: Install required packages
    package:
      name:
        - gnupg2
      state: present

- name: Configure firewalld on RHEL 8 node 3
  hosts: node3.lkerner.internal
  become: yes
  tasks: 
  - name: Remove firewalld lab package
    package:
      name: firewalld
      state: absent
